modLoader="javafml"
loaderVersion="[41,)"
license="LGPLv3"
issueTrackerURL="https://github.com/yungnickyoung/YUNGs-Better-Strongholds/issues"

[[mods]]
	modId="betterstrongholds"
	version="${file.jarVersion}"
	displayName="YUNG's Better Strongholds"
	credits="Thanks so much to all my patrons!"
	authors="YUNGNICKYOUNG, Acarii"
	description="A complete redesign of Minecraft's strongholds"
	logoFile="logo.png"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/yungs-better-strongholds"

[[dependencies.betterstrongholds]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"

[[dependencies.betterstrongholds]]
    modId="forge"
    mandatory=true
    versionRange="[41.0.45,)"

[[dependencies.betterstrongholds]]
    modId="yungsapi"
    versionRange="[1.19-Forge-3.4.0,)"
    mandatory=true
    ordering="NONE"
    side="BOTH"